version: "1"

services:

  notification_app:
    build:
      context: .
    container_name: notification-app
    ports:
      - 8004:8000
    restart: always
    depends_on:
      faust_app:
        condition: service_started
      zookeeper:
        condition: service_started
      kafka:
        condition: service_started

  faust_app:
    build:
      ./faust_app/
    container_name: faust-app
    command: bash -c ". entrypoint.sh"
    ports:
      - 8081:8081
    environment:
      SMTP_HOST: smtp.timeweb.ru
      SMTP_PORT: 465
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    env_file:
      - ./.env
    restart: always
    depends_on:
      zookeeper:
        condition: service_started
      kafka:
        condition: service_started

  nginx-app:
    image: nginx:latest
    container_name: nginx-app
    ports:
      - 84:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notification.rule=Host(`notification.tesseractmaks.tech`)"
    depends_on:
      notification_app:
        condition: service_started

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: notification-zookeeper
    ports:
      - 2181:2181
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: notification-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

networks:
  default:
    name: proxynet
    external: true
